### ISSUE TITLE
Image does not work in a VM

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/cosmic#13]
# Description

I tried both cosmic base image and cosmic-silverblue images in Virtual Machine Manager and both have a flickering problem when trying to start the cosmic-greeter service. This is a known issue, but I wanted to document it here in case others try to use our images in a VM. 

![image](https://github.com/ublue-os/cosmic/assets/4983138/e85ca7ac-2083-4d26-96ac-a41f5ef590c8)

**Comment by arindam-giri** [comment]
Same here in virtual box. but greeter is running
[Kooha-2024-03-06-19-17-59.webm](https://github.com/ublue-os/cosmic/assets/18495475/65ea26da-3e3d-4a90-a12d-b98929037358)

**Comment by tfmoraes** [comment]
Changing video to qxl worked for me on gnome-boxes.

**Comment by noelmiller** [comment]
> Changing video to qxl worked for me on gnome-boxes.

I'll give this a shot when I have the chance.

**Comment by blonde0091** [comment]
Changing to QXL in virt-manager does fix the issue of not being able to boot into the login screen for me

**Comment by ryanabx** [comment]
FYI here's why

![image](https://github.com/ublue-os/cosmic/assets/56272643/6d2bb7bf-9cea-49c1-8263-c4c4663a96d1)
