### ISSUE TITLE
Login from cosmic-greeter causes panick

### ISSUE THREAD

**Issue by PJansky** [ublue-os/cosmic#33]
Loging in with cosmic-greeter causes a panick on my qemu virtual machine based on fedora silverblue with the response: 
```
thread 'main' panicked at greetd/src/session/worker.rs:280:14:
unable to exec: EACCES
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace
```
This is possibly due to my many attempts with rollbacks in between to get cosmic working (it was because I was using the virtio graphics driver instead of QXL). Loging in from GDM seems to work fine though

**Comment by ryanabx** [comment]
This is the currently the only reason why we have to disable SELinux to use COSMIC on Fedora.

There's currently a problem logging into a COSMIC session from cosmic-greeter with SELinux set to Enforced

Set SELinux to 'Permissive' and try it again.

Sorry for the inconvenience 😕

**Comment by PJansky** [comment]
Thanks a lot, that's the issue
