### ISSUE TITLE
Will there now be cosmic-nvidia?

### ISSUE THREAD

**Issue by Rerum02** [ublue-os/cosmic#38]
Due to the recent announcement that Nvidia 555 drivers will be in the next image for some you ubue projects, Will we see Nvidia versions of cosmic?

**Comment by ahoneybun** [comment]
There isn't a different version of COSMIC for NVIDIA, it sounds like you just want an updated OS image with the new NVIDIA driver.

**Comment by Rerum02** [comment]
Yes, that is what I meant, like how there is a [kinoite-nvidia](https://github.com/ublue-os/hwe/pkgs/container/kinoite-nvidia)

**Comment by m2Giles** [comment]
There should now be Nvidia images. Reminder that this is pre-alpha software.

**Comment by castrojo** [comment]
https://github.com/orgs/ublue-os/packages?repo_name=cosmic has the list of the nvidia images if you wanna try them!
