### ISSUE TITLE
Access denied to ghcr.io

### ISSUE THREAD

**Issue by idnovic** [ublue-os/cosmic#72]
We can not build ontop the cosmic image anymore. We get this error. Has anyone an idea what is going on?

```

Error: GET https://ghcr.io/token?scope=repository%3Aublue-os%2Fcosmic-base%3Apull&service=ghcr.io: DENIED: requested access to the resource is denied
main.go:69: error during command execution: GET https://ghcr.io/token?scope=repository%3Aublue-os%2Fcosmic-base%3Apull&service=ghcr.io: DENIED: requested access to the resource is denied
```
full log: https://github.com/secureblue/secureblue/actions/runs/10483945214/job/29037481618

We can build every other image from ublue-os. 
This error started a few days ago.

**Comment by ryanabx** [comment]
Looks like someone renamed the `cosmic-base` image to `cosmic`. I'm not sure who, but git blaming these lines would tell you:

https://github.com/ublue-os/cosmic/blob/main/.github/workflows/build.yml#L80-L82

Sorry for the inconvenience, try changing cosmic-base to cosmic in your CI

**Comment by idnovic** [comment]
Thank you. This fixed our issue.
